### PR TITLE
WIP Issue 73

### PR DESCRIPTION
**Pull request by scottleedavis**
Issue #73 

Adds post dropdown menu + submenu for scheduling

### CODE REVIEW

**Comment by scottleedavis** [comment]
Screen Shot 2019-07-30 at 12 11 52 PM

**Comment by scottleedavis** [comment]
requires release v5.16.0

**Comment by andrey-yantsen** [comment]
Hey @scottleedavis! Few days ago v5.18 was released... any chance you can continue with this pull request?

**Comment by frcho** [comment]
Hey @scottleedavis! Any chance you can continue with this pull request?

**Comment by scottleedavis** [comment]
@hanzei @kaakaa would either of you be able to pick up and improve what I started please?

**Comment by scottleedavis** [comment]
@frcho I am not able to contribute currently.  i did contribute the submenu functionality needed in MM-webapp
https://github.com/mattermost/mattermost-webapp/pull/3357

**Comment by scottleedavis** [comment]
I will gift a $50 amazon gift card to the first person who completes this PR.  And some Mattermost stickers.
IMG_0645 copy

**Comment by zifeo** [comment]
@scottleedavis awesome job! Do you have some news when this might be merged? That would be a huge step for people migrating onto Mattermost.

**Comment by benbernard** [comment]
Hey @scottleedavis I see you're asking for help on this issue, what is required to get it across the line? Some updates / tests passing or.... ?

I'd love to help, as I love this feature in slack

**Comment by kaakaa** [comment]
Hi @benbernard 
I took a look into this PR, and I think this feature could be made to work with a few more tweaks (e.g.: [my work](https://github.com/kaakaa/mattermost-plugin-remind/commit/6ceea986d507e2f5668c19c028ff5f053353836e)).
However, while I was working on this, I found a CSS issue in the Mattermost codebase, so I think we'll have to fix it before this. (It's difficult for me due to my little knowledge about css...)
https://github.com/mattermost/mattermost-plugin-demo/issues/101

**Pull request closed without merging**
